<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- cdn bootstrap css -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" href="/css/estilos.css">

	<title>Mi pagina</title>
</head>
<body>
	<header>		
		<!-- barra de navegacion -->
		<nav class="navbar navbar-inverse">
		  <div class="container-fluid">		    
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="/index">Sistema ventas</a>
		    </div>
		    
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">		      	
		      </ul>
		      
		      <ul class="nav navbar-nav navbar-right">
		      	<?php if($this->action == "login"): ?>
		        	<li><a href="<?php echo $this->url(array('controller'=>'auth','action'=>'signin')) ?>">Registrarse</a></li>		        
		        <?php elseif($this->action == "registrarse"):?>
		        	<li><a href="<?php echo $this->url(array('controller'=>'auth','action'=>'login')) ?>">Iniciar sesion</a></li>		        
		        <?php endif; ?>
		      </ul>
		    </div>
		  </div>
		</nav>
	  <!-- /barra de navegacion -->
	</header>
	<!-- contendo de las vistas -->
	<?php echo $this->layout()->content; ?>	
	<!-- cdn de jquery-->
	<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
	<!-- cdn de js bootstrap -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>
